Clarified nr of bound states vs max quantum nr in PoschlTeller
ohno/Antique.jl pull request #63
Opened 2024-06-07 17:45 UTC by lhapp27

I clarified the difference between the number of bound states and the maximum quantum number in the documentation for the Pöschl-Teller model. The same issue should exist for models in which we count `n` from 0, and which have a finite number of bound states, i.e. the Morse potential.

2024-06-07 17:53 UTC, lhapp27 commented
I'm sorry for not updating the fork before merging, hence leading to "conflicts".

2024-06-08 12:34 UTC, ohno requested changes
Thank you for your efforts. Please check comments.

2024-06-08 12:34 UTC, ohno commented on docs/src/PoschlTeller.md
> +Note that the number of bound states is `nₘₐₓ + 1`, since we count the ground state from `n=0`.
Please write this line into the docstring.

2024-06-08 12:34 UTC, ohno commented on docs/src/PoschlTeller.md
> +Note that the number of bound states is `nₘₐₓ + 1`, since we count the ground state from `n=0`.
Here too.

2024-06-08 12:34 UTC, ohno commented on src/PoschlTeller.jl
I would like to discard the commit to this file. We don't need change this file if `0 <= n <= n_max` has been correct. Please pull latest version and update the docstrings.

2024-06-09 17:57 UTC, ohno commented
Please see 2 pages:
- https://ohno.github.io/Antique.jl/stable/MorsePotential/
- https://ohno.github.io/Antique.jl/stable/PoschlTeller/

The changes are as follows:
- I updated changed "Number of Bound States" to "Maximum Quantum Number" (68db3f5).
- I added tests for nr of bound states vs max quantum nr in PoschlTeller and MorsePotential (b331273). $0 < E_{n+1} - E_n$ must be satisfied for $0 \leq n \leq n_\mathrm{max}$.

2024-06-09 23:33 UTC, closed without merging